import {readFile,writeFile,mkdir,copyFile,cp} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
const root=path.dirname(fileURLToPath(import.meta.url));
const out=path.join(root,'docs');
const themeCSS=await readFile(path.join(root,'theme.css'),'utf8');
const themeJS=await readFile(path.join(root,'theme.js'),'utf8');
const themeHead=`<style id="siteThemeStyle">${themeCSS}</style><script id="siteThemeScript">${themeJS}</script>`;
const mathCSS=await readFile(path.join(root,'math-format.css'),'utf8');
const mathJS=await readFile(path.join(root,'math-format.js'),'utf8');
const mathHead=base=>`<style>${mathCSS}</style><script>${mathJS}</script><script src="${base}vendor/mathjax/tex-svg-full.js" defer></script>`;
const posts=JSON.parse(await readFile(path.join(root,'content/posts.json'),'utf8')).sort((a,b)=>b.date.localeCompare(a.date));
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const seen=new Set();
for(const p of posts){if(!/^[a-z0-9-]+$/.test(p.slug)||seen.has(p.slug)||!/^\d{4}-\d{2}-\d{2}$/.test(p.date)||!/^[-a-z0-9]+\.html$/.test(p.lesson))throw Error('Invalid or duplicate post metadata');seen.add(p.slug)}
const date=s=>new Date(s+'T12:00:00Z').toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric',timeZone:'UTC'});
const head=(title,description,base)=>`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title)} · MATH 10675</title><meta name="description" content="${escape(description)}"><link rel="icon" href="${base}favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="${base}style.css">${themeHead}${mathHead(base)}</head><body><a class="skip" href="#main">Skip to content</a><header class="site-header"><a class="brand" href="${base}index.html"><span class="mark" aria-hidden="true">Δ</span><span>MATH 10675<small>Interactive class notebook</small></span></a><nav aria-label="Site navigation"><a href="${base}index.html#archive">Lessons</a><a href="${base}index.html#about">About</a></nav></header>`;
const footer=()=>`<footer><span>MATH 10675 · Fall 2026</span></footer></body></html>`;
const status=p=>p.status?`<p class="draft-status">${escape(p.status)}</p>`:'';
const tags=p=>`<ul class="tags" aria-label="Topics">${p.topics.map(t=>`<li>${escape(t)}</li>`).join('')}</ul>`;
const art=`<svg class="cover" viewBox="0 0 500 330" role="img" aria-label="A graph linking two values with horizontal and vertical change arrows"><defs><marker id="arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M0 0L10 5L0 10Z" fill="#d9b06b"/></marker></defs><path d="M70 65V265H450" stroke="#8da79b" stroke-width="2" fill="none"/><path d="M70 130H450M70 195H450M165 65V265M260 65V265M355 65V265" stroke="#527567" fill="none"/><path d="M90 245L165 215L355 97L435 65" stroke="#e9eee1" stroke-width="4" fill="none"/><path d="M165 215H355" stroke="#d9b06b" stroke-width="3" stroke-dasharray="7 5" marker-end="url(#arrow)" fill="none"/><path d="M355 215V97" stroke="#d9b06b" stroke-width="3" stroke-dasharray="7 5" marker-end="url(#arrow)" fill="none"/><circle cx="165" cy="215" r="8" fill="#e9eee1"/><rect x="347" y="89" width="16" height="16" fill="#d9b06b"/><g fill="#fff" font-family="Georgia,serif" font-size="25"><text x="250" y="245">Δx</text><text x="375" y="163">Δy</text></g><text x="70" y="35" fill="#c5d6ca" font-family="system-ui" font-size="13" letter-spacing="2">TWO VALUES. ONE CHANGE.</text></svg>`;
await mkdir(path.join(out,'posts'),{recursive:true});await mkdir(path.join(out,'lessons'),{recursive:true});
const first=posts[0];
const home=head('Interactive class notebook','Interactive lessons and slides for MATH 10675. Explore quantities, variables, graphs, and mathematical reasoning.','')+`<main id="main"><section class="intro"><p class="eyebrow">Fall 2026 · Class blog</p><h1>Interactive class lessons</h1><p>Interactive investigations and slides for MATH 10675, with problem scenarios, adjustable graphs, and self-check exercises.</p></section><section id="archive" aria-labelledby="archive-title"><div class="section-heading"><h2 id="archive-title">The lesson notebook</h2><span>${posts.length} ${posts.length===1?'investigation':'investigations'}</span></div>${posts.map((p,i)=>`<article class="lesson-card"><div class="lesson-copy">${status(p)}<p class="eyebrow">${escape(p.module)} · ${escape(p.investigations)}</p><h3><a href="posts/${p.slug}.html">${escape(p.title)}</a></h3><time datetime="${p.date}">${date(p.date)}</time><p>${escape(p.description)}</p>${tags(p)}<div class="actions"><a class="button" href="lessons/${p.lesson}">Open interactive lesson <span aria-hidden="true">↗</span></a><a class="text-link" href="posts/${p.slug}.html">Read lesson notes →</a></div></div>${i===0?`<a class="lesson-art" href="posts/${p.slug}.html" aria-label="Lesson notes: ${escape(p.title)}">${art}</a>`:''}</article>`).join('')}</section><section id="about" class="about"><p class="eyebrow">About this notebook</p><h2>Using the lessons</h2><div><p>Each lesson includes its problem context, interactive controls, and opportunities to check your reasoning. Open a lesson directly, or read its notes first for an overview.</p><p>New interactive slides and investigations will join this archive throughout the class. Activities work on desktop and mobile. Answers stay in the open lesson and are cleared when you reload; nothing is submitted.</p></div></section></main>`+footer();
await writeFile(path.join(out,'index.html'),home);
for(const p of posts){const html=head(p.title,p.description,'../')+`<main id="main" class="post"><a class="back" href="../index.html#archive">← All lessons</a><p class="eyebrow">${escape(p.module)} · ${escape(p.investigations)}</p><h1>${escape(p.title)}</h1>${status(p)}<time datetime="${p.date}">${date(p.date)}</time><p class="lede">${escape(p.description)}</p>${tags(p)}<a class="button" href="../lessons/${p.lesson}">Open interactive lesson ↗</a><h2>Inside this investigation</h2><ol class="outline">${p.sections.map(s=>`<li><h3>${escape(s.title)}</h3><p>${escape(s.text)}</p></li>`).join('')}</ol><aside class="source"><h2>Sources and adaptations</h2><p>${escape(p.sourceNote)}</p></aside><a class="back" href="../index.html#archive">← Back to the lesson notebook</a></main>`+footer();await writeFile(path.join(out,'posts',p.slug+'.html'),html);let lesson=await readFile(path.join(root,'lessons',p.lesson),'utf8');lesson=lesson.replace('</head>',themeHead+mathHead('../')+'</head>').replace('<body>','<body><div class="lesson-toolbar"><a href="../index.html">← MATH 10675 · All lessons</a></div>');await writeFile(path.join(out,'lessons',p.lesson),lesson)}
await copyFile(path.join(root,'style.css'),path.join(out,'style.css'));await copyFile(path.join(root,'favicon.svg'),path.join(out,'favicon.svg'));await writeFile(path.join(out,'.nojekyll'),'');
await cp(path.join(root,'vendor'),path.join(out,'vendor'),{recursive:true});
if(process.argv.includes('--standalone')){
  const engine=await readFile(path.join(root,'vendor/mathjax/tex-svg-full.js'),'utf8');
  for(const p of posts){let source=await readFile(path.join(root,'lessons',p.lesson),'utf8');source=source.replace('</head>',themeHead+`<style>${mathCSS}</style><script>${mathJS}</script><script>${engine}</script>`+'</head>');await writeFile(path.join(root,'..',p.lesson),source)}
}

console.log(`Built ${posts.length} lesson post(s) and interactive lesson(s) in docs/.`);
